server:
  port: 8011
  servlet:
    context-path: /
spring:
  profiles:
    active: test
  application:
    name: huoshenshan
  #jdbc基本配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:/mapping/*Mapper.xml
